version: "3"
services:
    app:
        restart: always
        build: .
        ports:
          - 5000:5000
        environment:
            - FLASK_APP=app.py
        command: flask run --host=0.0.0.0 #--port=5000
        depends_on:
            - db
    db:
        restart: always
        image: postgres:13.4-buster
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=F!4s37js7J
            - POSTGRES_DB=postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        # ports:
        #     - 5432:5432
volumes:
    db-data:
    